# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='group',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Dialog'),
        ),
    ]
