# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170616_0738'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InDialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.DateTimeField(auto_now_add=True)),
                ('exit_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='timestamp',
            new_name='sending_time',
        ),
        migrations.RemoveField(
            model_name='dialogmember',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='dialogmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user_id',
        ),
        migrations.AddField(
            model_name='dialog',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialog',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialog',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dialogmember',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='messages',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DialogMember'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='reading_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 16, 7, 37, 26, 516802, tzinfo=utc),),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indialog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.DialogMember'),
        ),
    ]
