# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170616_0738'),
        ('chat', '0002_auto_20170616_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogmember',
            name='dialog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.Dialog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dialogmember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
            preserve_default=False,
        ),
    ]
